### ISSUE TITLE
[Bug] Spacing of text on mobile view

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/current-website#10]
![image](https://user-images.githubusercontent.com/34355337/57296850-eab35400-70c5-11e9-9597-bdca6e22fa89.png)

**Comment by giventofly** [comment]
tamanho da altura ou do texto? Texto justificado não me parece boa ideia (como está actualmente), se for a linha, é só aumentar (achava que tinha posto já, mas posso ter-me esquecido).

Qual das duas é? horizontalmente ou verticalmente?

**Comment by JorgeMiguelGomes** [comment]
@giventofly I think that the problem is the text's justification, that should be eliminated.
