### ISSUE TITLE
[Feat] Text align 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/current-website#11]
![image](https://user-images.githubusercontent.com/34355337/57296939-23ebc400-70c6-11e9-9055-10437751fd13.png)

Text should be aligned with text from team. 
Align avatars with function & description of team member.

**Comment by giventofly** [comment]
Não acho que seja boa ideia extender o texto porque fica dificil de se ler tantas linhas, e a alinhar seria com o "max-width" criado. do miguel até ao fim do "bloco" do membro de equipa. Só é problema em ecras "grandes", mas faz-se se for preciso.

**Comment by JorgeMiguelGomes** [comment]
Ok, agreed. 
Regarding the team elements' alignment, what do you think @giventofly?

**Comment by miguelantoniosantos** [comment]
@giventofly are you currently working on this issue?

**Comment by giventofly** [comment]
@JorgeMiguelGomes I like the way it is specially because it's now a slider, in bigger screens maybe add another item - update js and css accordingly. I wouldn't change.

@Cotemero I missed the reply, updated with question regarding the issue.

**Comment by miguelantoniosantos** [comment]
What is the final action regarding this issue?

**Comment by JorgeMiguelGomes** [comment]
@Cotemero please update according to @giventofly's suggestions "_in bigger screens maybe add another item - update js and css accordingly._"
