### ISSUE TITLE
[Feat] Newsletter section 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/current-website#12]
Create custom field(s) so that the website admin can insert the text and the code for whatever newsletter system they choose to use. 
![Screenshot 2019-05-07 at 14 11 56](https://user-images.githubusercontent.com/34355337/57302006-23f1c100-70d2-11e9-8063-482b69adcf03.png)

**Comment by miguelantoniosantos** [comment]
Should it swap all of the html containing the text input and subscribe button?

**Comment by giventofly** [comment]
Thought it would be  done hardcoded, never used a custom field to insert JS/HTML and my documentation search seemed to not be possible without a hack (could be wrong).

**Comment by miguelantoniosantos** [comment]
Changes are online, RFC

**Comment by miguelantoniosantos** [comment]
Implemented with no objections
