### ISSUE TITLE
[Feat] Change text and link color for contact section

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/current-website#13]
The text and link colours should e white and light grey to contrast with the background picture.

**Comment by miguelantoniosantos** [comment]
Is this complete or still requires changes?

**Comment by JorgeMiguelGomes** [comment]
Still requires changes

**Comment by miguelantoniosantos** [comment]
Fixed, RFC

**Comment by miguelantoniosantos** [comment]
Implemented with no objections
