### ISSUE TITLE
[Feat] Change "Advisories" page title to "Conselhos VOST"

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/current-website#14]
Apparently the page title is hardcoded. Either create a custom field to edit the page title **or** change it to "Conselhos VOST" 
https://vost.pt/advisories/ 
![Screenshot 2019-05-12 at 16 15 41](https://user-images.githubusercontent.com/34355337/57584285-41a79780-74d1-11e9-8eb7-767028280e92.png)

**Comment by miguelantoniosantos** [comment]
Isn't this a new website?

**Comment by JorgeMiguelGomes** [comment]
Different functions: 
advisory.vost.pt is a sub-domain to embed posts into Video Website Cards on Twitter.

**Comment by miguelantoniosantos** [comment]
Changed it to "Conselhos VOST". Adding the custom field

**Comment by miguelantoniosantos** [comment]
Done
