### ISSUE TITLE
[Bug] Posts won't move to trash 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/current-website#7]
When the user trashes a post, it redirects to an URL similar to "https://vost.pt/?trashed=1&ids=707" which is not a normal behaviour.

**Comment by giventofly** [comment]
Seems to be a occurrence related to the http headers: https://wordpress.org/support/topic/wp-5-1-1-clicking-trash-on-the-posts-page-wrongly-redirects-to-domain-root/ .

A "hack" solution is to on the post list select the item, and use the bulk action to move to trash.

**Comment by miguelantoniosantos** [comment]
Unable to replicate, Asking for more details

**Comment by giventofly** [comment]
Create a post, inside of it click on trash. It will move to trash and redirect to domain/?trashed instead of keeping in the same position: domain/posts.php.

**Comment by miguelantoniosantos** [comment]
On Nginx configuration the Referrer-Policy was set to _origin_, swapped it to _same-origin_

**Comment by miguelantoniosantos** [comment]
Re open as it is being reported again

**Comment by miguelantoniosantos** [comment]
@JorgeMiguelGomes The Post name can not be empty, can you try again with a draft with a title?

**Comment by miguelantoniosantos** [comment]
Solved
