### ISSUE TITLE
[Feat]] Cookies Text

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/current-website#8]
Texto para cookies: "Na VOST Portugal somos totalmente transparentes. Enquanto estiveres no nosso site não vamos usar o teu computador para minar moedas virtuais, ou outras más práticas. // AT VOST Portugal we are totally transparent. While you are checking our site we won't use your computer to virtual currencies, or any other bad practices"

**Comment by giventofly** [comment]
Na parte da configuração da página tem uma secção que diz: Social & cookie & g analytics, e dentro tem "cookie consent", é aí que se coloca o texto.

Vou colocar este para as duas linguas.
